---
title: "Data Load"
output:
  pdf_document: default
  html_document: default
---
```{r}
#Install packages and load libraries 
library(readxl)
library(tidyverse)
library(openxlsx)
library(sandwich)
library(lmtest)
```


```{r}
#Read in respective raw data files and save to data frames.  
state_policies <- read_excel("~/w203_lab2_group1/data/raw/state_policies.xlsx")
mobility_report <- read.csv("~/w203_lab2_group1/data/raw/mobility_report.csv")
demographic <- read.csv("~/w203_lab2_group1/data/raw/demographic_data.csv")
covid_cases <- read.csv("~/w203_lab2_group1/data/raw/covid_cases.csv")
```

```{r}
# the beginning of previous week for mobility
pre_mobile_begin <- as.Date("2020-06-21")
pre_mobile_end <- as.Date("2020-06-27")
# the beginning of current week for mobility
mobile_begin <- as.Date("2020-06-28")
mobile_end <- as.Date("2020-07-04")
# the beginning of previous week for covid
pre_covid_begin <- as.Date("2020-07-12")
covid_begin <- as.Date("2020-07-19")
```


```{r}
#Start exploring and cleaning state_policies data set. 
head(state_policies)

#Pull out the columns we want for face mask use.
state_policies <- state_policies[c("STATE", "POSTCODE", "FIPS", "FM_ALL", "FM_ALL2", "FM_END")]

#Need to trim first four rows, but first we'll give better variable names
state_policies <- 
  state_policies %>%
  rename(
    state = STATE, 
    postcode = POSTCODE, 
    fips = FIPS, 
    fm_first_mandate = FM_ALL, 
    fm_second_mandate = FM_ALL2, 
    fm_end = FM_END
    )
state_policies

#Trim first four rows (describing data)
state_policies <- state_policies[-1:-4,]

#Adjust the date columns to have a properly formatted date.
state_policies$fm_first_mandate <- openxlsx::convertToDate(state_policies$fm_first_mandate)
state_policies$fm_second_mandate <- openxlsx::convertToDate(state_policies$fm_second_mandate)
state_policies$fm_end <- openxlsx::convertToDate(state_policies$fm_end)

#Replace all '1899-12-30' with NA
state_policies[state_policies == '1899-12-30'] <- NA

#Add a flag for mask mandate in place as of 07/01 (mandate in place for the majority of our week of interest)
state_policies['public_mask_mandate_flag'] <- ifelse(state_policies$fm_first_mandate <= '2020-07-01' & (state_policies$fm_end > '2020-07-04' | is.na(state_policies$fm_end)) | state_policies$fm_second_mandate <= '2020-07-01', 1, 0)

# Replace NA values with 0
state_policies$public_mask_mandate_flag <- ifelse(is.na(state_policies$public_mask_mandate_flag),0,state_policies$public_mask_mandate_flag)

# Drop rows with NA values for state name 
state_policies <- state_policies %>% drop_na(state)

# Write the state policies data frame to a csv file
write.csv(state_policies,
          "~/w203_lab2_group1/data/cleaned/clean_state_policies.csv", 
          row.names = TRUE)
```


```{r clean mobility data, echo=TRUE, message=TRUE}
#For state level need sub_region_1 = 'state' and sub_region_2 is blank
mobility_report <- mobility_report[which(mobility_report$sub_region_1 != '' & mobility_report$sub_region_2 == ''),]

#Cast date to date type
mobility_report <- mobility_report %>% mutate(date=as.Date(date))

# Keep the columns of interest
mobility_report <- mobility_report %>% select(date, sub_region_1, contains('percent_change'))

# Abbreviate the column names
mobility_report <- 
  mobility_report %>%
  rename(
    state = sub_region_1,
    retail_rec = retail_and_recreation_percent_change_from_baseline,
    grocery_rx = grocery_and_pharmacy_percent_change_from_baseline,
    parks = parks_percent_change_from_baseline,
    transit = transit_stations_percent_change_from_baseline,
    workplaces = workplaces_percent_change_from_baseline,
    residential = residential_percent_change_from_baseline
  )

# Create the time intervals of interest
pre_mobile_week <- filter(mobility_report, date>=pre_mobile_begin & date<=pre_mobile_end)
mobile_week <- filter(mobility_report, date >= mobile_begin & date<=mobile_end)

# Add a column for 7 days after the date for the join
pre_mobile_week <- pre_mobile_week %>% mutate(post_date = date + 7)

# Create a data frame with the pre and post dates and metrics 
state_mobility <- dplyr::left_join(pre_mobile_week, mobile_week, by = c("state", "post_date" = "date"), copy = FALSE, suffix = c("_p1", "_p2"))

# Keep only columns of interest
state_mobility <- state_mobility %>% rename(start_date = date, end_date = post_date)
```

```{r, subset and process mobility data for desired time period, echo=TRUE, message=TRUE}
# Calculate the difference in percent change in mobility between each day of the week pair
state_mobility <- state_mobility %>%
  mutate(
    retail_rec_change = retail_rec_p2 - retail_rec_p1,
    grocery_rx_change = grocery_rx_p2 - grocery_rx_p1,
    parks_change = parks_p2 - parks_p1,
    transit_change = transit_p2 - transit_p1,
    workplace_change = workplaces_p2 - workplaces_p1,
    residential_change = residential_p2 - residential_p1,
  )

# Write the state mobility data frame with all sectors to a csv file
write.csv(state_mobility,
          "~/w203_lab2_group1/data/cleaned/state_mobility.csv", 
          row.names = TRUE)

#Create filtered df for retail that we will use to pivot wide and create a column for each day of week (each independent variable in our model). 
state_mobility_retail <- state_mobility[c("state","end_date", "retail_rec_change")]

state_mobility_retail['end_date'] <- as.character(state_mobility_retail$end_date)

#Rename deltas to which day of the week they represent
state_mobility_retail$end_date <- factor(state_mobility_retail$end_date, 
                                         levels = c('2020-06-28', '2020-06-29','2020-06-30', '2020-07-01','2020-07-02','2020-07-03','2020-07-04'),
                                         labels = c('Sunday_retail','Monday_retail','Tuesday_retail','Wednesday_retail','Thursday_retail','Friday_retail','Saturday_retail'))

#Pivot wide so that we have one row per state, with day of week mobility changes in separate columns. 
state_mobility_retail <- state_mobility_retail %>% pivot_wider(names_from = end_date, values_from = retail_rec_change)

# Write the retail data frame to a csv file
write.csv(state_mobility_retail,
          "~/w203_lab2_group1/data/cleaned/state_mobility_retail.csv", 
          row.names = TRUE)


#Create filtered df for Grocery that we will use to pivot wide and create a column for each day of week (each independent variable in our model). 
state_mobility_groc <- state_mobility[c("state","end_date", "grocery_rx_change")]

state_mobility_groc['end_date'] <- as.character(state_mobility_groc$end_date)

#Rename deltas to which day of the week they represent
state_mobility_groc$end_date <- factor(state_mobility_groc$end_date, 
                                         levels = c('2020-06-28', '2020-06-29','2020-06-30', '2020-07-01','2020-07-02','2020-07-03','2020-07-04'),
                                         labels = c('Sunday_groc','Monday_groc','Tuesday_groc','Wednesday_groc','Thursday_groc','Friday_groc','Saturday_groc'))

#Pivot wide so that we have one row per state, with day of week mobility changes in separate columns. 
state_mobility_groc <- state_mobility_groc %>% pivot_wider(names_from = end_date, values_from = grocery_rx_change)

state_mobility_groc

# Write the grocery data frame to a csv file
write.csv(state_mobility_groc,
          "~/w203_lab2_group1/data/cleaned/state_mobility_groc.csv", 
          row.names = TRUE)


#Create filtered df for parks that we will use to pivot wide and create a column for each day of week (each independent variable in our model). 
state_mobility_parks <- state_mobility[c("state","end_date", "parks_change")]

state_mobility_parks['end_date'] <- as.character(state_mobility_parks$end_date)

#Rename deltas to which day of the week they represent
state_mobility_parks$end_date <- factor(state_mobility_parks$end_date, 
                                         levels = c('2020-06-28', '2020-06-29','2020-06-30', '2020-07-01','2020-07-02','2020-07-03','2020-07-04'),
                                         labels = c('Sunday_parks','Monday_parks','Tuesday_parks','Wednesday_parks','Thursday_parks','Friday_parks','Saturday_parks'))

#Pivot wide so that we have one row per state, with day of week mobility changes in separate columns. 
state_mobility_parks <- state_mobility_parks %>% pivot_wider(names_from = end_date, values_from = parks_change)

state_mobility_parks

# Write the parks data frame to a csv file
write.csv(state_mobility_parks,
          "~/w203_lab2_group1/data/cleaned/state_mobility_parks.csv", 
          row.names = TRUE)


#Create filtered df for transit that we will use to pivot wide and create a column for each day of week (each independent variable in our model). 
state_mobility_transit <- state_mobility[c("state","end_date", "transit_change")]

state_mobility_transit['end_date'] <- as.character(state_mobility_transit$end_date)

#Rename deltas to which day of the week they represent
state_mobility_transit$end_date <- factor(state_mobility_transit$end_date, 
                                         levels = c('2020-06-28', '2020-06-29','2020-06-30', '2020-07-01','2020-07-02','2020-07-03','2020-07-04'),
                                         labels = c('Sunday_transit','Monday_transit','Tuesday_transit','Wednesday_transit','Thursday_transit','Friday_transit','Saturday_transit'))

#Pivot wide so that we have one row per state, with day of week mobility changes in separate columns. 
state_mobility_transit <- state_mobility_transit %>% pivot_wider(names_from = end_date, values_from = transit_change)

state_mobility_transit

# Write the transit data frame to a csv file
write.csv(state_mobility_transit,
          "~/w203_lab2_group1/data/cleaned/state_mobility_transit.csv", 
          row.names = TRUE)


#Create filtered df for transit that we will use to pivot wide and create a column for each day of week (each independent variable in our model). 
state_mobility_work <- state_mobility[c("state","end_date", "workplace_change")]

state_mobility_work['end_date'] <- as.character(state_mobility_work$end_date)

#Rename deltas to which day of the week they represent
state_mobility_work$end_date <- factor(state_mobility_work$end_date, 
                                         levels = c('2020-06-28', '2020-06-29','2020-06-30', '2020-07-01','2020-07-02','2020-07-03','2020-07-04'),
                                         labels = c('Sunday_work','Monday_work','Tuesday_work','Wednesday_work','Thursday_work','Friday_work','Saturday_work'))

#Pivot wide so that we have one row per state, with day of week mobility changes in separate columns. 
state_mobility_work <- state_mobility_work %>% pivot_wider(names_from = end_date, values_from = workplace_change)

state_mobility_work

# Write the work data frame to a csv file
write.csv(state_mobility_work,
          "~/w203_lab2_group1/data/cleaned/state_mobility_work.csv", 
          row.names = TRUE)


#Create filtered df for transit that we will use to pivot wide and create a column for each day of week (each independent variable in our model). 
state_mobility_residential <- state_mobility[c("state","end_date", "residential_change")]

state_mobility_residential['end_date'] <- as.character(state_mobility_residential$end_date)

#Rename deltas to which day of the week they represent
state_mobility_residential$end_date <- factor(state_mobility_residential$end_date, 
                                         levels = c('2020-06-28', '2020-06-29','2020-06-30', '2020-07-01','2020-07-02','2020-07-03','2020-07-04'),
                                         labels = c('Sunday_residential','Monday_residential','Tuesday_residential','Wednesday_residential','Thursday_residential','Friday_residential','Saturday_residential'))

#Pivot wide so that we have one row per state, with day of week mobility changes in separate columns. 
state_mobility_residential <- state_mobility_residential %>% pivot_wider(names_from = end_date, values_from = residential_change)

state_mobility_residential

# Write the residential data frame to a csv file
write.csv(state_mobility_residential,
          "~/w203_lab2_group1/data/cleaned/state_mobility_residential.csv", 
          row.names = TRUE)
```

```{r clean cases data}
#Start exploring covid_cases data set. 
covid_cases

#Reformat character type to date type
covid_cases$date <- as.Date(covid_cases$date)

#Subset to dates of interest. 
covid_cases <- covid_cases[which(covid_cases$date >= '2020-07-12' & covid_cases$date <= '2020-07-25'),]

#Create columns for each date to make it easy to calculate deltas 
covid_cases <- covid_cases[c('state','date','cases')] %>% pivot_wider(names_from = date, values_from = cases)

#Create new columns that are simple delta calculations 
covid_cases['p1_change_in_cases'] <- covid_cases['2020-07-18'] - covid_cases['2020-07-12']

covid_cases['p2_change_in_cases'] <- covid_cases['2020-07-25'] - covid_cases['2020-07-19']

#Our primary outcome variable of interest, week over week percent change in new cases
covid_cases['p1_p2_percent_change_in_cases'] <- ((covid_cases['p2_change_in_cases'] / covid_cases['p1_change_in_cases']) - 1) * 100

covid_cases

# Write the cleaned covid cases dataframe to a csv file
write.csv(covid_cases,
          "~/w203_lab2_group1/data/cleaned/clean_covid_cases.csv", 
          row.names = TRUE)
```


```{r}
#Start exploring demographic dataset. 

#Only looking for columns with column name ending with PE to get percentages by state. 
demographic <- demographic %>% 
  dplyr:: select(NAME, ends_with("PE"))


#Filter down to variables of interest
demographic <- demographic[c("NAME", "DP05_0003PE", "DP05_0005PE", "DP05_0006PE", "DP05_0007PE", "DP05_0008PE", "DP05_0009PE", "DP05_0015PE", "DP05_0016PE", "DP05_0017PE","DP05_0037PE")]

#Rename variables
demographic <- demographic %>%
  rename(state = NAME, percent_female = DP05_0003PE, percent_under_5 = DP05_0005PE, percent_5_to_9 = DP05_0006PE, percent_10_to_14 = DP05_0007PE, percent_15_to_19 = DP05_0008PE, percent_20_to_24 = DP05_0009PE, percent_65_to_74 = DP05_0015PE, percent_75_to_84 = DP05_0016PE, percent_85_plus = DP05_0017PE, percent_white = DP05_0037PE)

#Drop first row (description)
demographic <- demographic[-1,]

#Cast character percentages as double and rejoin to state in dataframe. 
demographic <- data.frame(demographic["state"], sapply(demographic[,-1], as.numeric))

#Sum age breakouts into under 24 and over 65 groups
demographic["percent_under_24"] = demographic$percent_under_5 + demographic$percent_5_to_9 + demographic$percent_10_to_14 + demographic$percent_15_to_19 + demographic$percent_20_to_24

demographic["percent_over_65"] = demographic$percent_65_to_74 + demographic$percent_75_to_84 + demographic$percent_85_plus

demographic
#Filter out columns we no longer need (all the age breakouts). 
demographic <- demographic[c("state", "percent_female", "percent_white", "percent_under_24", "percent_over_65")]

demographic

# Write the demographic data frame to a csv file
write.csv(demographic,
          "~/w203_lab2_group1/data/cleaned/cleaned_demographic.csv", 
          row.names = TRUE)
```


```{r join cleaned dataframes}
#Join cleaned dataframes into final dataframe for analysis. 

df <- state_mobility_retail %>% left_join(demographic, by = "state") %>%
left_join(state_mobility_groc[c("state",'Sunday_groc','Monday_groc','Tuesday_groc','Wednesday_groc','Thursday_groc','Friday_groc','Saturday_groc')], by = "state") %>%
left_join(state_mobility_parks[c("state",'Sunday_parks','Monday_parks','Tuesday_parks','Wednesday_parks','Thursday_parks','Friday_parks','Saturday_parks')], by = "state") %>%
left_join(state_mobility_transit[c("state",'Sunday_transit','Monday_transit','Tuesday_transit','Wednesday_transit','Thursday_transit','Friday_transit','Saturday_transit')], by = "state") %>%
left_join(state_mobility_work[c("state",'Sunday_work','Monday_work','Tuesday_work','Wednesday_work','Thursday_work','Friday_work','Saturday_work')], by = "state") %>%
left_join(state_mobility_residential[c("state",'Sunday_residential','Monday_residential','Tuesday_residential','Wednesday_residential','Thursday_residential','Friday_residential','Saturday_residential')], by = "state") %>%
left_join(covid_cases[c("state","p1_p2_percent_change_in_cases")], by = "state") %>% left_join(state_policies[c("state","public_mask_mandate_flag")], by = "state")

df

# Write the final data frame to a csv file
write.csv(df,
          "~/w203_lab2_group1/data/cleaned/df.csv", 
          row.names = TRUE)
```


```{r begin to evaluate model}
short_model <- lm(p1_p2_percent_change_in_cases ~ Sunday_retail + Monday_retail + Tuesday_retail + Wednesday_retail + Thursday_retail + Friday_retail + Saturday_retail, data = df)
medium_model <- lm(p1_p2_percent_change_in_cases ~ Sunday_retail + Monday_retail + Tuesday_retail + Wednesday_retail + Thursday_retail + Friday_retail + Saturday_retail + public_mask_mandate_flag, data = df)
full_model <- lm(p1_p2_percent_change_in_cases ~ Sunday_retail + Monday_retail + Tuesday_retail + Wednesday_retail + Thursday_retail + Friday_retail + Saturday_retail + public_mask_mandate_flag + percent_female + percent_white + percent_under_24 + percent_over_65,data = df)

summary(short_model)
summary(medium_model)
summary(full_model)
```