---
title: "Data Load"
output:
  pdf_document: default
  html_document: default
---
```{r, warning=FALSE, echo=FALSE}
#Install packages and load libraries 

#Pastecs for nice, quick summary features of our datasets. 
#install.packages("pastecs", repos = "http://cran.us.r-project.org")

library("readxl")
#library("pastecs")
library("tidyverse")
library("openxlsx")
library(dplyr)
library(zoo)
library(gridExtra)
```


```{r, warning=FALSE, echo=FALSE}
#Read in respective raw data files and save to dataframes.  
state_policies <- read_excel("~/w203_lab2_group1/data/raw/state_policies.xlsx")
mobility_report <- read.csv("~/w203_lab2_group1/data/raw/mobility_report.csv")
demographic <- read.csv("~/w203_lab2_group1/data/raw/demographic_data.csv")
covid_cases <- read.csv("~/w203_lab2_group1/data/raw/covid_cases.csv")
clean_state_policies <- read.csv('~/w203_lab2_group1/data/cleaned/clean_state_policies.csv')
clean_df <- read.csv('~/w203_lab2_group1/data/cleaned/df.csv')
```

```{r, warning=FALSE, echo=FALSE}
#Start exploring and cleaning state_policies dataset. 
#Pull out the columns we want for facemask use.
state_policies <- state_policies[c("STATE", "POSTCODE", "FIPS", "FM_ALL", "FM_ALL2", "FM_END")]

#Need to trim first four rows, but first we'll give better variable names
state_policies <- 
  state_policies %>%
  rename(
    state = STATE, 
    postcode = POSTCODE, 
    fips = FIPS, 
    fm_first_mandate = FM_ALL, 
    fm_second_mandate = FM_ALL2, 
    fm_end = FM_END
    )

#Trim first four rows (describing data)
state_policies <- state_policies[-1:-4,]


#Adjust the date columns to have a properly formatted date.
state_policies$fm_first_mandate <- openxlsx::convertToDate(state_policies$fm_first_mandate)
state_policies$fm_second_mandate <- openxlsx::convertToDate(state_policies$fm_second_mandate)
state_policies$fm_end <- openxlsx::convertToDate(state_policies$fm_end)

#Replace all '1899-12-30' with NA
state_policies[state_policies == '1899-12-30'] <- NA
```

```{r, warning=FALSE, echo=FALSE}
#Start exploring mobility_report dataset. 
# head(mobility_report)

#For state level need sub_region_1 = 'state' and sub_region_2 is blank
mobility_report <- mobility_report[which(mobility_report$sub_region_1 != '' & mobility_report$sub_region_2 == ''),]

```

```{r, warning=FALSE, echo=FALSE}
#Start exploring demographic dataset. 
# demographic

#Only looking for columns with column name ending with PE to get percentages by state. 
demographic <- demographic %>% 
  dplyr:: select(NAME, ends_with("PE"))

```

```{r, warning=FALSE, echo=FALSE}
#Start exploring covid_cases dataset. 
# covid_cases

covid_cases$date <- as.Date(covid_cases$date)
# Add new cases
covid_cases <- covid_cases %>% group_by(fips) %>% mutate(new_cases=c(NA, diff(cases)))

covid_cases_november <- covid_cases[which(covid_cases$date >= '2020-10-01' & covid_cases$date <= '2020-11-07'),]
```

```{r, warning=FALSE, echo=FALSE}
# Smooth mobility data and look at states

get_plots <- function(mobility, covid_cases, state_var) {

mobility_report <- mobility

covid_cases$date <- as.Date(covid_cases$date)
# Add new cases
covid_cases <- covid_cases %>% group_by(fips) %>% mutate(new_cases=c(NA, diff(cases)))
  
mob_ny <- mobility_report %>% mutate(date=as.Date(date)) %>% filter(sub_region_1==state_var)  %>% filter(sub_region_2=='')
mob_ny_smooth <- mob_ny %>% mutate(
  retail_smooth=rollmean(x=retail_and_recreation_percent_change_from_baseline, 7, na.pad=TRUE, align="right"),
  grocery_smooth=rollmean(x=grocery_and_pharmacy_percent_change_from_baseline, 7, na.pad=TRUE, align="right"),
  transit_smooth=rollmean(x=transit_stations_percent_change_from_baseline, 7, na.pad=TRUE, align="right"),
  park_smooth=rollmean(x=parks_percent_change_from_baseline, 7, na.pad=TRUE, align="right"),
  resid_smooth=rollmean(x=residential_percent_change_from_baseline, 7, na.pad=TRUE, align="right"),
  work_smooth=rollmean(x=workplaces_percent_change_from_baseline, 7, na.pad=TRUE, align="right"),
)

covid_ny <- covid_cases %>% filter(state==state_var) %>% mutate(new_cases_smooth=rollmean(x=new_cases, 7, na.pad=TRUE, align="right"))
joined <- left_join(covid_ny, mob_ny_smooth, by='date')

retail_plot <- joined %>% ggplot(aes(x=date)) + geom_line(aes(y=retail_smooth)) + 
  geom_line(aes(y=new_cases_smooth / 1000), color='green') + scale_x_date(date_labels = "%m")

grocery_plot <- joined %>% ggplot(aes(x=date)) + geom_line(aes(y=grocery_smooth)) + 
  geom_line(aes(y=new_cases_smooth / 1000), color='green') + scale_x_date(date_labels = "%m")

transit_plot <- joined %>% ggplot(aes(x=date)) + geom_line(aes(y=transit_smooth)) + 
  geom_line(aes(y=new_cases_smooth / 1000), color='green') + scale_x_date(date_labels = "%m")

park_plot <- joined %>% ggplot(aes(x=date)) + geom_line(aes(y=park_smooth)) + 
  geom_line(aes(y=new_cases_smooth / 1000), color='green') + scale_x_date(date_labels = "%m")

resid_plot <- joined %>% ggplot(aes(x=date)) + geom_line(aes(y=resid_smooth)) + 
  geom_line(aes(y=new_cases_smooth / 1000), color='green') + scale_x_date(date_labels = "%m")

work_plot <- joined %>% ggplot(aes(x=date)) + geom_line(aes(y=work_smooth)) + 
  geom_line(aes(y=new_cases_smooth / 1000), color='green') + scale_x_date(date_labels = "%m")

plots <- grid.arrange(
  retail_plot,
  grocery_plot,
  transit_plot,
  park_plot,
  resid_plot,
  work_plot,
  nrow = 3
)

return(plots)
}
```

```{r}
plots <- get_plots(mobility_report, covid_cases, "California")
```


```{r}
covid_cases_fm <- left_join(covid_cases, state_policies, by='state')
```

```{r}
M <- cor(mobility_report[, c(10: 15)] %>% rename(retail=retail_and_recreation_percent_change_from_baseline, grocery=grocery_and_pharmacy_percent_change_from_baseline, parks=parks_percent_change_from_baseline, transit=transit_stations_percent_change_from_baseline, workspaces=workplaces_percent_change_from_baseline, resid= residential_percent_change_from_baseline) %>% drop_na())

corrplot(M, method='circle')
```